# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20190122_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Products'),
        ),
    ]
