# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-06 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20190129_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Products'),
        ),
    ]
