# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-07 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20190206_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='MRP',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Products'),
        ),
    ]
